version: '3.4'

services:
  customerwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  bookwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

